routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::Get('/', function(){
    return view('admin.index');
}); 

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', 'AdminController@index')->name('admin');

Route::resource('ingresos', 'IngresoController');

Route::get('/cartera', 'CarteraController@index')->name('cartera');

Route::resource('/egresos', 'EgresosController');

app/Egresos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Egresos extends Model
{
    //Valores de los egresos 
    protected $table = 'movimientos';

    protected $fillable = ['Nombre', 'Valor', 'Estado', 'EstadoMeta', 'TipoMovimiento', 'Usuario'];
}

app/Http/Controllers/EgresosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Egresos;
use Illuminate\Support\Facades\Redirect;
use DB;

class EgresosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Se muestra toda la informacion y se redireje a la pestaña
        $egresos = Egresos::join('users', 'movimientos.Usuario','=','users.id')
                    ->select('movimientos.id', 'movimientos.Nombre', 'movimientos.Valor', 'movimientos.Estado', 'movimientos.TipoMovimiento', 'users.name')
                    ->where([
                        ['TipoMovimiento', '=', '2'],
                        ['Estado', '=', '1'],
                    ])->orderBy('Id', 'desc')
                    ->Get();

        return view('Admin.egresos.index', ['egresos' => $egresos]);

    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Se inserta nuevo egreso a la BD
        $Egresos = New Egresos();
        $Egresos->Nombre = $request->Nombre;
        $Egresos->Valor = $request->Valor;
        $Egresos->Estado = '1';
        $Egresos->EstadoMeta = '0';
        $Egresos->TipoMovimiento = '2';
        $Egresos->Usuario = '1';
        $Egresos->save();
        return Redirect::to('egresos');
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Editar los datos de los egresos segun id 
        $egresos = Egresos::findOrFail($request->id_Egreso);
        $egresos->Nombre = $request->Nombre;
        $egresos->Valor = $request->Valor;
        $egresos->Estado = '1';
        $egresos->EstadoMeta = '0';
        $egresos->TipoMovimiento = '2';
        $egresos->Usuario = '1';
        $egresos->save();
        return Redirect::to('egresos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Egresos $egreso)
    {
        //Se modifican el ingreso para que no se muestre en la vista
        $egreso = Egresos::find($egreso->id);

        //Se cambia el estado del egreso
        $egreso->Estado='0';
        $egreso->save();
        return redirect('/egresos');
    }
}

resources/views/Admin/egresos/form.blade.php
<div class="form-group row">
    <label class="col-md-3 form-control-label" for="text-input">Nombre</label>
    <div class="col-md-9">
        <input type="text" id="Nombre" name="Nombre" class="form-control" placeholder="Nombre de egreso" required >
        <span class="help-block">(*) Ingrese el nombre del egreso</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 form-control-label" for="text-input">Valor del egreso</label>
    <div class="col-md-9">
        <input type="number" id="Valor" name="Valor" class="form-control" placeholder="Valor del egreso" required>
        <span class="help-block">(*) Ingrese el valor del egreso</span>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-warning" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-success">Guardar</button>
</div>

resources/views/Admin/egresos/index.blade.php
@extends('Admin.layouts.dashboard')
@section('content')
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Egresos</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Gestor de los egresos, Aqui se podra ingresar, editar y eliminar los egresos</li>
            </ol>
            <a href="/cartera" class="btn btn-success btn-block">Ver valor en cartera</a>
            <button type="button" class="btn btn-warning btn-block text-white" data-toggle="modal" data-target="#modalNuevo">Crear Egreso</button>
            <br>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Lista de los egresos
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Identificador</th>
                                    <th>Nombre</th>
                                    <th>Valor</th>
                                    <th>Usuario</th>
                                    <th>Editar</th>
                                    <th>Eliminar</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Identificador</th>
                                    <th>Nombre</th>
                                    <th>Valor</th>
                                    <th>Usuario</th>
                                    <th>Editar</th>
                                    <th>Eliminar</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach ($egresos as $egreso)
                                    <tr>
                                        <td>{{$egreso->id}}</td>
                                        <td>{{$egreso->Nombre}}</td>
                                        <td>{{$egreso->Valor}}</td>
                                        <td>{{$egreso->name}}</td>
                                        <td>
                                            <button type="submit" class="btn btn-success btn-sm" data-id_egreso="{{$egreso->id}}" data-nombre="{{$egreso->Nombre}}" data-valor="{{$egreso->Valor}}" data-toggle="modal" data-target="#modalEditarEgreso">
                                                <i class="far fa-edit"></i>
                                            </button>    
                                        </td>
                                        <td>
                                            <form action="/egresos/{{$egreso->id}}" method="post">
                                                @method('DELETE')
                                                @csrf
                                                <button type="submit" class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
                                            </form>
                                            
                                            
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <!--Inicio del modal agregar-->
    <div class="modal fade" id="modalNuevo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-primary modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Agregar Egreso</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('egresos.store')}}" method="post" class="form-horizontal">
                       {{csrf_field()}}
                       @include('Admin.egresos.form') 
                    </form> 
                </div>
                
            </div>
            
        </div>
        
    </div>

    <div class="modal fade" id="modalEditarEgreso" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-primary modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Editar egreso</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('egresos.update', 'test')}}" method="post" class="form-horizontal">
                        {{--  --}}
                        {{method_field('patch')}}
                        {{csrf_field()}}
                        
                        <input type="hidden" id="id_Egreso" name="id_Egreso" value="">

                        @include('Admin.egresos.form')
                    </form> 
                </div>
                
            </div>
            
        </div>
        
    </div>

@endsection