routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::Get('/', function(){
    return view('admin.index');
}); 

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', 'AdminController@index')->name('admin');

Route::resource('ingresos', 'IngresoController');

Route::get('/cartera', 'CarteraController@index')->name('cartera');

Route::resource('/egresos', 'EgresosController');

app/Ingreso.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ingreso extends Model
{
    //Modelo de los ingresos del sistema
    protected $table = 'movimientos';

    protected $fillable = ['Nombre', 'Valor', 'Estado', 'EstadoMeta', 'TipoMovimiento', 'Usuario'];
}

app/Http/Controllers/IngresoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ingreso;
use Illuminate\Support\Facades\Redirect;
use DB;

class IngresoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $ingresos = Ingreso::join('users', 'movimientos.Usuario','=','users.id')
                    ->select('movimientos.id', 'movimientos.Nombre', 'movimientos.Valor', 'movimientos.Estado', 'movimientos.EstadoMeta', 'movimientos.TipoMovimiento', 'users.name')
                    ->where([
                        ['TipoMovimiento', '=', '1'],
                        ['Estado', '=', '1'],
                    ])->orderBy('Id', 'desc')
                    ->Get();

        return view('Admin.ingresos.index', ['ingresos' => $ingresos]);
        //return $ingresos;

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Este metodo nos permite listar las categorias
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Se inserta nuevo ingrsos a la BD
        $ingresos = New Ingreso();
        $ingresos->Nombre = $request->Nombre;
        $ingresos->Valor = $request->Valor;
        $ingresos->Estado = '1';
        $ingresos->EstadoMeta = '0';
        $ingresos->TipoMovimiento = '1';
        $ingresos->Usuario = '1';
        $ingresos->save();
        return Redirect::to('ingresos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //Editar los registros de los ingresos segun id 
        $ingresos = Ingreso::findOrFail($request->id_Ingreso);
        $ingresos->Nombre = $request->Nombre;
        $ingresos->Valor = $request->Valor;
        $ingresos->Estado = '1';
        $ingresos->EstadoMeta = '0';
        $ingresos->TipoMovimiento = '1';
        $ingresos->Usuario = '1';
        $ingresos->save();
        return Redirect::to('ingresos');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ingreso $ingreso)
    {
        //Cambiar de estado algun ingreso 
        $ingreso = Ingreso::find($ingreso->id);

        //Se cambia el estado al post
        $ingreso->Estado='0';
        $ingreso->save();
        return redirect('/ingresos');
    }
}

resources/views/Admin/ingresos/form.blade.php
<div class="form-group row">
    <label class="col-md-3 form-control-label" for="text-input">Nombre</label>
    <div class="col-md-9">
        <input type="text" id="Nombre" name="Nombre" class="form-control" placeholder="Nombre de ingreso" required >
        <span class="help-block">(*) Ingrese el nombre del ingreso</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-md-3 form-control-label" for="text-input">Valor del ingreso</label>
    <div class="col-md-9">
        <input type="number" id="Valor" name="Valor" class="form-control" placeholder="Valor del ingreso" required>
        <span class="help-block">(*) Ingrese el valor del ingreso</span>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-warning" data-dismiss="modal">Cerrar</button>
    <button type="submit" class="btn btn-success">Guardar</button>
</div>

resources/views/Admin/ingresos/index.blade.php
@extends('admin.layouts.dashboard')

{{-- Contenido desde el layout de admin --}}
@section('content')
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Ingresos</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Gestor de ingreso, Aqui podras agregar editar y eliminar ingresos</li>
            </ol>
            <a href="/cartera" class="btn btn-success btn-block">Ver valor en cartera</a>
            <button type="button" class="btn btn-warning btn-block" data-toggle="modal" data-target="#modalNuevo">Crear Ingreso</button>
            <br>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Lista de ingresos
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Identificador</th>
                                    <th>Nombre</th>
                                    <th>Valor</th>
                                    <th>Meta asig</th>
                                    <th>Usuario</th>
                                    <th>Editar</th>
                                    <th>Eliminar</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Identificador</th>
                                    <th>Nombre</th>
                                    <th>Valor</th>
                                    <th>Meta asig</th>
                                    <th>Usuario</th>
                                    <th>Editar</th>
                                    <th>Eliminar</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach ($ingresos as $ingreso)
                                    <tr>
                                        <td>{{$ingreso->id}}</td>
                                        <td>{{$ingreso->Nombre}}</td>
                                        <td>{{$ingreso->Valor}}</td>
                                        <td>{{$ingreso->EstadoMeta}}</td>
                                        <td>{{$ingreso->name}}</td>
                                        <td>
                                            <button type="submit" class="btn btn-success btn-sm" data-id_ingreso="{{$ingreso->id}}" data-nombre="{{$ingreso->Nombre}}" data-valor="{{$ingreso->Valor}}" data-toggle="modal" data-target="#modalEditar">
                                                <i class="far fa-edit"></i>
                                            </button>    
                                        </td>
                                        <td>
                                            @if ($ingreso->EstadoMeta == 0)
                                                <form action="/ingresos/{{$ingreso->id}}" method="post">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
                                                </form>
                                            @else
                                                ASOCIADO A META
                                            @endif
                                            
                                            
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>


    <!--Inicio del modal agregar-->
    <div class="modal fade" id="modalNuevo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-primary modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Agregar Ingreso</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('ingresos.store')}}" method="post" class="form-horizontal">
                       {{csrf_field()}}
                       @include('Admin.ingresos.form') 
                    </form> 
                </div>
                
            </div>
            
        </div>
        
    </div>



    <div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-primary modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Editar Ingreso</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('ingresos.update', 'test')}}" method="post" class="form-horizontal">
                        {{method_field('patch')}}
                        {{csrf_field()}}
                        
                        <input type="hidden" id="id_Ingreso" name="id_Ingreso" value="">

                        @include('Admin.ingresos.form')
                    </form> 
                </div>
                
            </div>
            
        </div>
        
    </div>


@endsection